# Generated by Django 4.2.8 on 2024-12-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
