# Generated by Django 4.2.8 on 2024-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
