# Generated by Django 4.2.8 on 2024-12-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0004_userregistration_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_ID', models.CharField(max_length=50)),
                ('Amount', models.IntegerField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.userregistration')),
            ],
        ),
    ]
