# Generated by Django 5.1.2 on 2024-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0005_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi',
            name='Amount',
            field=models.CharField(max_length=50),
        ),
    ]
