# Generated by Django 5.1.2 on 2024-12-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0006_alter_upi_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashondelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.userregistration')),
            ],
        ),
    ]
