# Generated by Django 5.1.2 on 2024-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_remove_card_name_remove_cashondelivery_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upi',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
