# Generated by Django 5.1.2 on 2024-12-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0010_upi_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='phoneno',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
