# Generated by Django 5.1.2 on 2025-01-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0012_card_user_cashondelivery_user_upi_user_finalprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finalprice',
        ),
    ]
