# Generated by Django 5.1.2 on 2025-01-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0013_delete_finalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalprice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.userregistration')),
            ],
        ),
    ]
