# Generated by Django 5.1.2 on 2025-01-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0014_finalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.cartdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.userregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='finalprice',
        ),
    ]
