# Generated by Django 5.1.2 on 2025-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0015_finalorder_delete_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='finalprice',
            field=models.IntegerField(default=0),
        ),
    ]
