# Generated by Django 5.1.2 on 2025-01-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0016_finalorder_finalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cashondelivery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upi',
            name='user',
        ),
    ]
