# Generated by Django 5.1.2 on 2025-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0017_remove_card_user_remove_cashondelivery_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='productdata',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
