# Generated by Django 5.1.2 on 2025-01-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0018_alter_finalorder_productdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='productdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.cartdata'),
        ),
    ]
