# Generated by Django 5.1.2 on 2025-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0019_alter_finalorder_productdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='mobile_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='paymentmode',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
