# Generated by Django 5.1.2 on 2025-01-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0020_finalorder_address_finalorder_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='productdata',
            field=models.CharField(max_length=50),
        ),
    ]
