# Generated by Django 5.1.2 on 2025-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0021_alter_finalorder_productdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='productdata',
            new_name='productname',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='price',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='quantity',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='unit',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
